exclude:
- /pet-shop-ui/pet-shop-ui-rest/src/content/resources/rest/.*
- /pet-shop-ui/pet-shop-ui-app/src/content/resources/web/js/lib/.*
- /pet-shop-ui/pet-shop-ui-app/src/content/resources/web/js/require.js
component_depth: 3
languages:
- java
- javascript
