language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - docker
addons:
  sonarcloud:
    organization: pet-shop
    token:
      secure: fyhs02kBz7XU5fhdS915ujAWGMQHQx2cdsx03xt5e7atcd3HNomMdiaIGGBiUswbHSpGgRA12vCvzYxfXWns8AnxLvzP/665cNCzRbtgzRvk5eIwYYKdTK1rnvo7WbhL6oEwTCTjcIcr8MTK2tmmAYB+v31XSeWkzg2d4EBTQBkZtp0sTsaf8ptYbJ96W7Fb8nw1IhMHsWQHkdhFv827hvGe1oat7MrWpuj+8HN/ndILJrYDC8jnSLb9pdgYrMZ7Opt90tpBLAA8sPG7ziBub/looShFWzX4rcufwEsNPFF9KaWAvK8pmFcfS0rFE0WvoeAvIhs7YRQdWdzQk2HtpBisIu94zEG9r6gNZEenQXb53KTGqOJkeVRjW5L1eW/CVtFICpv2krmxxz/Rs4eL0Q2z9v3GEQt7PK/QZ7qOldHmUM0DFkyrbEvqHQTLPGCORGdL/o+JxVH6SO0g/7KYmZSrOQ9meegD+Uq/beGVLz2u+IKHHfYA66r0yVBWnSzkqZYTosVYly2JHUFC7i11PrD2kOE99IYd+iPAZp2hK9gp2tiVwIQ1eqPvXhA4K2MOZ1L9lB6W7B/aGfeqWsds3Xk1AsxYO/w1pcB6EtCYAewQZIPvxo/b/suWP5urFzIQsBygGJ6SGt+jcCxm7zBzy5reTncz0sD7IhbF9Dzkj+U=
before_script:
  - sudo service postgresql stop
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=pet-shop_pet-shop
notifications:
  email:
    recipients:
      - secure: bYRKnB/F9rlzgpVCktZlqO+oCu2vqXrMof7DT3nUzowCXbqGusa2sUczbY37ynVlIUHDR67yQr6rBgWm7DJQU8V4njXrqUTfZcEtuaVQwulfSrKrHBFmSWY26gINEcPkOmysS0nYjVCH0zoOjDM+4B/xd+8JyBZyLNeDEabWtTRaHrXhUrZFY3xXbv1wm+SKG8QcthuIAZ39yGA9qLWX2aPTDru1m7xBmUgVECrMBRjHR5CtCBK5OXJzp+KuTd77AnmOtZ33QVjZtHnhakRVHHNkLpBETR8vEa+Y6NBSfrHH4m7TugKV8nn8nPl69fCdO1wi6PZYjJBAwPqiQn48NS7tJPJvcDHxdjWFp3tTRW8I57MfUyq/ph2uAzmbVz6RZIbn/G/WWFedji3/yxWK28+nNLfGKxH/E1IctIzNF16iUe+kwbsabvyZfRcSXtp6Pj0Y/+ZztD4v1f0BaU6OqG8VyIszErI5QE/nTXXuF3RU29CXgajAiRHagupMk2RROR/r9+u7hnufAAiwylKwNVl1pt3kyMDpP8kC5Pko6UYt8kJtLuvMdmM4uhg2iVv2+cQj/fdy3HG04Hn2pV0bmcu/6QDy+Pt3IliwEHd/cJEyJ2J2QAAFi0HpdYznO9GTzqpQHskyU4Thy8Zz3j/+GBqJwnay95xZG3FeLHTG3XM=