language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  sonarqube: true
env:
  global:
    - secure: H367GF5Rzr8z4y6O2+JhlYSSEwNd7fL9aymHiqfYhk0xAYfk4fW8HwPnH1AcYWurR/Y3lursAvqs2na8BfC+fOt1O6qtvj69z8N4qGz/j3gW2wlmtgFAbEOft63R6D0TkKcUUSEe4+hAwrTjuBvJsgjP4cELwe3zY3FL5ubr3bma4dpSEkSVYfTonjRXmURcTzP3vvtPZgQxLX3GAUBoxlyu2vCKHqQgIBA7GcHvMnV20LjH3eYYTgKfU2bOq/1A7WANX2Ctgbo6j1Tnk+nt2WyK23mmO/5Q53LeVEA3f2B3n6YsBypX41d8DMRAHrCJPJkI10iYIrE3woPkCvhrwrcrAfAa7M8Iz/jGRlbRZbM2HytNBWoldzB0qUD6Vy6cAOirxxXhI2dzKqLWRZdYDuF3fI/UIDvktQFXe5/8xn/LjqzY9i8hzvKIo7q1M8AJ00/Is1rn7fZNWPjrFD/rqVCjJUe9lNaiecr9aMOC5BD1t8G/Zu2OJ/uLtRavGXSZ/SoS84Qr/zUt2P39/2mOiEpoVdV5w1R62RkDiR5X7ebI6zVe3v8Zkg6coy09WSf4fxnV0OW4w1fQSI1eAMGAObOu/G3oKIcga1KqZEa8bxcRdVVuR05rNyfdhLQVnfe9FJzUebp0hSEGBuIkAzGGec42rGRYanDDvYrSOdnXjZk=
before_script:
  - psql -c "create database shop_test;" -U postgres
  - psql -c "create user shop_test with password 'password';" -U postgres
  - psql -c "grant all privileges on database shop_test to shop_test;" -U postgres
script:
  - mvn test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
notifications:
  email:
    recipients:
      - secure: bYRKnB/F9rlzgpVCktZlqO+oCu2vqXrMof7DT3nUzowCXbqGusa2sUczbY37ynVlIUHDR67yQr6rBgWm7DJQU8V4njXrqUTfZcEtuaVQwulfSrKrHBFmSWY26gINEcPkOmysS0nYjVCH0zoOjDM+4B/xd+8JyBZyLNeDEabWtTRaHrXhUrZFY3xXbv1wm+SKG8QcthuIAZ39yGA9qLWX2aPTDru1m7xBmUgVECrMBRjHR5CtCBK5OXJzp+KuTd77AnmOtZ33QVjZtHnhakRVHHNkLpBETR8vEa+Y6NBSfrHH4m7TugKV8nn8nPl69fCdO1wi6PZYjJBAwPqiQn48NS7tJPJvcDHxdjWFp3tTRW8I57MfUyq/ph2uAzmbVz6RZIbn/G/WWFedji3/yxWK28+nNLfGKxH/E1IctIzNF16iUe+kwbsabvyZfRcSXtp6Pj0Y/+ZztD4v1f0BaU6OqG8VyIszErI5QE/nTXXuF3RU29CXgajAiRHagupMk2RROR/r9+u7hnufAAiwylKwNVl1pt3kyMDpP8kC5Pko6UYt8kJtLuvMdmM4uhg2iVv2+cQj/fdy3HG04Hn2pV0bmcu/6QDy+Pt3IliwEHd/cJEyJ2J2QAAFi0HpdYznO9GTzqpQHskyU4Thy8Zz3j/+GBqJwnay95xZG3FeLHTG3XM=
deploy:
  edge: true
  provider: cloudfoundry
  username:
    secure: trNBUVYogpOBPDmT+lBR687amIg/Pj2X2lOtKDYYOWGR5EPaB2bcII1FQ7JPiqT1wCjaTXb54tkRYFLkxeDhO5J3P1QJ32ebpvSn/UzNsljUMfVhaLJraMFbOaj8JmSvmJ5LtOlT8yvbYIC36I+MtT2YWxxyZPc0WPuC35d6Ezdwurkv4xNohrfGDF8XJcxiO//CHm9fsk16N4jdTUDA9iaJ7/nLerBqGU0u358x0p8g786hik/EbN186FiV3LmbUuzEpNWtlIUGWCzGyScqTi2yp77fzT+FiSMUBjBk2qbYRw9V9jnTHI5sn/gon1Q+ijRedX4ftEiap87NdYJ2w2OJf2ribZnpsi8hjW1wgwZ0dQIDR+MCsQW2/x2T0QI+YV9EXBG5yF3K0IvMGKmg600GcV2tEW0Stn7DKMVzHU2QRN6Cy4k7LG9+elvgIIfW/irrPqt3WQzJhkGLVdIXcn+Rpn2EDTs/YaaGoRyHeX4iLifcfXMlrC2w2tdmSGPI1Czm1rYmWySSu+1pDwadK2Upz1SoxP26ziuNP7yFT0OpTPySICIUiuIeCdC4xG4KNdbr23L5bnSePJCgLIbALLtgbhyg3ZeWbIyIKG1DJRU1X/Rf2LI0H1XXV1GkKWIs4Uo+blWZsbJKIHFKLZ4mC2G1KXbvvLmXeLC42+Xt+lE=
  password:
    secure: KXV1XMQ9GnQV+qWGXSFLxNnYhaGrXCgvysabiHfCt+bv7GlNZEZo5lqn7WG9zkcEmG/qjDUBnlTOKMeHJmvYaygLsoB716VzvpY6F99K+VR+13t5uAQlPGbXoqdtxN75OA1+VubXC4HONK7RMf1KjqovmQLIHu1kGot81EV7KyOcXXpEVBBky69vWGIAVAzJj567fX+MmoCVfD/ahcswRYl9OVndwnOk6fmWBxQX0EXhwzNJyYHnaP0b5aq1+sszv/GHPLI42WClkzUJXpBQVr+NpU+dlbxqBWPd+faYNs81aFcbhmyeM83pUWUmpyionTlXmy19pQYCX1hqgwia7DHBTo1dyQFU3kNqgqeelhSgaYThMjRVTEu1QDp4uaC5l9/COHa7alPELEAAKe622DjssEOj+sRZ+W0Lw+T5TKTEtWsRafCfz7leU4VyL7w4h6A3dAjwSZriK68WZvVXCNrbQ5oaal2yPdswz0gmObF7dlgv1KIasjbdI6aY+y+o0Bn0m+6BFO/V/Nzsbwjv72eWSfzMXl4ABsX7JoQXY8zfU6l8lvqbC/xV5w2JOeMnxd4UkM7T6BzyqMu6yoHKFoyRRzlLe1/R9KhsaVeAGnGJibjJnCEq7ZxjGwNEJ1VNZTPq+/SOq8uIFR8PLuCUfSA3E4xpRnOFu99jX8nw9Ck=
  api: https://api.run.pivotal.io
  organization: pet-shop
  space: development