language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  sonarqube: true
env:
  global:
    - secure: H367GF5Rzr8z4y6O2+JhlYSSEwNd7fL9aymHiqfYhk0xAYfk4fW8HwPnH1AcYWurR/Y3lursAvqs2na8BfC+fOt1O6qtvj69z8N4qGz/j3gW2wlmtgFAbEOft63R6D0TkKcUUSEe4+hAwrTjuBvJsgjP4cELwe3zY3FL5ubr3bma4dpSEkSVYfTonjRXmURcTzP3vvtPZgQxLX3GAUBoxlyu2vCKHqQgIBA7GcHvMnV20LjH3eYYTgKfU2bOq/1A7WANX2Ctgbo6j1Tnk+nt2WyK23mmO/5Q53LeVEA3f2B3n6YsBypX41d8DMRAHrCJPJkI10iYIrE3woPkCvhrwrcrAfAa7M8Iz/jGRlbRZbM2HytNBWoldzB0qUD6Vy6cAOirxxXhI2dzKqLWRZdYDuF3fI/UIDvktQFXe5/8xn/LjqzY9i8hzvKIo7q1M8AJ00/Is1rn7fZNWPjrFD/rqVCjJUe9lNaiecr9aMOC5BD1t8G/Zu2OJ/uLtRavGXSZ/SoS84Qr/zUt2P39/2mOiEpoVdV5w1R62RkDiR5X7ebI6zVe3v8Zkg6coy09WSf4fxnV0OW4w1fQSI1eAMGAObOu/G3oKIcga1KqZEa8bxcRdVVuR05rNyfdhLQVnfe9FJzUebp0hSEGBuIkAzGGec42rGRYanDDvYrSOdnXjZk=
before_script:
  - psql -c "create database shop_test;" -U postgres
  - psql -c "create user shop_test with password 'password';" -U postgres
  - psql -c "grant all privileges on database shop_test to shop_test;" -U postgres
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
notifications:
  email:
    recipients:
      - secure: bYRKnB/F9rlzgpVCktZlqO+oCu2vqXrMof7DT3nUzowCXbqGusa2sUczbY37ynVlIUHDR67yQr6rBgWm7DJQU8V4njXrqUTfZcEtuaVQwulfSrKrHBFmSWY26gINEcPkOmysS0nYjVCH0zoOjDM+4B/xd+8JyBZyLNeDEabWtTRaHrXhUrZFY3xXbv1wm+SKG8QcthuIAZ39yGA9qLWX2aPTDru1m7xBmUgVECrMBRjHR5CtCBK5OXJzp+KuTd77AnmOtZ33QVjZtHnhakRVHHNkLpBETR8vEa+Y6NBSfrHH4m7TugKV8nn8nPl69fCdO1wi6PZYjJBAwPqiQn48NS7tJPJvcDHxdjWFp3tTRW8I57MfUyq/ph2uAzmbVz6RZIbn/G/WWFedji3/yxWK28+nNLfGKxH/E1IctIzNF16iUe+kwbsabvyZfRcSXtp6Pj0Y/+ZztD4v1f0BaU6OqG8VyIszErI5QE/nTXXuF3RU29CXgajAiRHagupMk2RROR/r9+u7hnufAAiwylKwNVl1pt3kyMDpP8kC5Pko6UYt8kJtLuvMdmM4uhg2iVv2+cQj/fdy3HG04Hn2pV0bmcu/6QDy+Pt3IliwEHd/cJEyJ2J2QAAFi0HpdYznO9GTzqpQHskyU4Thy8Zz3j/+GBqJwnay95xZG3FeLHTG3XM=