language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - docker
addons:
  sonarcloud:
    organization: alkach-github
    token:
      secure: hYKTl6OKzcX8NwkrHcA7/00SgaESn+3Zm1a3epVV52hNadkyF+VJAoeSd7AIFnSvCZyTQB3Z7b9zZLDTqEAUZRTg0zFenmf2HuK6pr/77KRLbMx2L/ZKfQaWmot4WTdFWA6t7ko1zbAxUQ9yDzoNOik5MzZWt150dcHvj5mvOyDX536L+u48KP1Si3A25AMDMuOkIbqPC8Lv3WHG0KdBxmp0cEPCZUSWXWzFpF1PcyLHJocfCBNs3FlCR+QhYJbWLwR9j/kHy4QZChtnB+e0aAsHzjgfAfushu4wWmylEVUJ/iygaZK9NiscziIL8QuN+xav/FIOBtVxMvl9QQZFGTGHsTJIHX41/bTBVg4WejaCszY/AWrAscapg5f4dSWMyNjTICfy3maPHAcnxiI8xGTNWraRTmYqpIGbpmnm5QLKnnha01xWCfwwfyHLrY0+QKoKPJX3YJmCmffaj+oxmGaOKjcEFEvXN/wQ2dfrT7zkXyBX+03r8WAtsFfUPzUJ6c5Mr3J7aPB3RjFRTLMHUa0C+tSJTFJjdfmZ5WhRTuI7AxyYkIoO9Ue5/L7mAm3ru+nz2kRLZ08ZFyZmaznCT0Jc7pOKLSwE/xC8DZsK8gEn3hYTIH3Hlols3O8xu9oAqeZNr7vvFqyPBlViA49qKMbYHJmSJWtwpC9vYgxraXc=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
notifications:
  email:
    recipients:
      - secure: bYRKnB/F9rlzgpVCktZlqO+oCu2vqXrMof7DT3nUzowCXbqGusa2sUczbY37ynVlIUHDR67yQr6rBgWm7DJQU8V4njXrqUTfZcEtuaVQwulfSrKrHBFmSWY26gINEcPkOmysS0nYjVCH0zoOjDM+4B/xd+8JyBZyLNeDEabWtTRaHrXhUrZFY3xXbv1wm+SKG8QcthuIAZ39yGA9qLWX2aPTDru1m7xBmUgVECrMBRjHR5CtCBK5OXJzp+KuTd77AnmOtZ33QVjZtHnhakRVHHNkLpBETR8vEa+Y6NBSfrHH4m7TugKV8nn8nPl69fCdO1wi6PZYjJBAwPqiQn48NS7tJPJvcDHxdjWFp3tTRW8I57MfUyq/ph2uAzmbVz6RZIbn/G/WWFedji3/yxWK28+nNLfGKxH/E1IctIzNF16iUe+kwbsabvyZfRcSXtp6Pj0Y/+ZztD4v1f0BaU6OqG8VyIszErI5QE/nTXXuF3RU29CXgajAiRHagupMk2RROR/r9+u7hnufAAiwylKwNVl1pt3kyMDpP8kC5Pko6UYt8kJtLuvMdmM4uhg2iVv2+cQj/fdy3HG04Hn2pV0bmcu/6QDy+Pt3IliwEHd/cJEyJ2J2QAAFi0HpdYznO9GTzqpQHskyU4Thy8Zz3j/+GBqJwnay95xZG3FeLHTG3XM=