version: '3'
services:
  web:
    image: 'pet-shop-web:1.0'
    ports:
      - '9090:9090'
    depends_on:
      - application-db
  application-db:
    image: 'postgres:alpine'
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: password